### ISSUE TITLE
SyntaxError?

### ISSUE THREAD

**Issue by warloxian** [thehackingsage/hacktronian#22]
┌─[warloxian@asus705-linux]─[~/hacktronian]
└──╼ $sudo hacktronian
  File "/usr/share/doc/hacktronian/hacktronian.py", line 82
    print """
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(""")?

This happens if i run just hacktronian or sudo hacktronian on Parrot sec

**Comment by duckduckgeese** [comment]
me too running kali linux

**Comment by MrAppAndCrap** [comment]
Same here Kali linux on a rpi 2w
